GRENADE GAME: GameControls Class Reference
GameControls Class Reference
This is the MainWindow Class which is generated by the Ui file, if we wish to add anything to the main Ui we add it here.
#include <GameControls.h>
Public Member Functions
GameControls (QWidget *parent=0)
ctor basically we create a GameLogic and parent it to this window so our GameLogic is the main canvas
~GameControls ()
dtor
Protected Member Functions
void keyPressEvent (QKeyEvent *_event)
override the keyPressEvent inherited from QObject so we can handle key presses.
void keyReleaseEvent (QKeyEvent *_event)
Private Slots
void startGame ()
start game slot
void resetGame ()
reset game slot
void setBeginnerDifficulty ()
difficulty beginner radio
void setAdvancedDifficulty ()
difficulty advanced radio
void setLevelDisplay (int _levelDisplay)
level number display
void setCameraFromUI ()
to set the current selected camera
void setFreeCamFlagFromUI (int)
to detach the camera
Private Member Functions
void timerEvent (QTimerEvent *_event)
timerEvent to process the elapsed timers
void setPowerBar (float)
sets the power bar to reflect the power applied to the grenade
void setProgressBar ()
sets the progress bar to reflect the loading progress
void setRandomValueForWindLevel3 ()
sets the wind value got from gamelogic to reflect on the ui
float getCurrentScore ()
get the current score
void constructTheGame ()
construct the gl(GameLogic) window
Private Attributes
GameLogic * m_gl
our gl window created in GameLogic.h
Ui::GameControls * m_ui
our ui namespace
int m_gameRunning
timer to set after the game starts running, used to hide loading page
int m_settingWind
timer to set wind speed
int m_updateScore
timer to update the score after querying the GameLogic class
int isStartButtonClicked
to signal if the start button is clicked
QString ColorHigh
color style sheets to change the ui poer bars and score bars based on the current score
QString ColorIntermediate
QString ColorLow
QMovie * movieLeft
gif animations to display wind arrow marks
QMovie * movieRight
Detailed Description
This is the MainWindow Class which is generated by the Ui file, if we wish to add anything to the main Ui we add it here.
GameControls class to capture inputs and pass it through to next level of classes for processing and to update all the UI elements according to the specific state of the game by quering the GameLogic class.
Definition at line 25 of file GameControls.h.
Constructor & Destructor Documentation
GameControls::GameControls (QWidget * parent = 0)
ctor basically we create a GameLogic and parent it to this window so our GameLogic is the main canvas
Definition at line 8 of file GameControls.cpp.
References ColorHigh, ColorIntermediate, ColorLow, m_gl, m_settingWind, m_ui, m_updateScore, movieLeft, movieRight, resetGame(), setCameraFromUI(), setFreeCamFlagFromUI(), setLevelDisplay(), and startGame().
                       :
                        QMainWindow(_parent),
                        m_ui(new Ui::GameControls)
{
    // setup the user interface
    m_ui->setupUi(this);
    // first we re-size the window to the size we need
    this->resize(QSize(1024,720));
    // now create our GL window and parent it to this
   // m_gl = new GameLogic(this);
    m_gl = 0;
    // this is the window title
    this->setWindowTitle(QString("PRESS 'START GAME' TO START THE AWARD WINNING GRENADE THROW GAME "));
    connect(m_ui->m_startGame,SIGNAL(clicked()),this,SLOT(startGame()));
    connect(m_ui->m_levelSetDial,SIGNAL(sliderMoved(int)),this,SLOT(setLevelDisplay(int)));
    connect(m_ui->restartButton,SIGNAL(clicked()),this,SLOT(resetGame()));
    connect(m_ui->leftCamera,SIGNAL(clicked()),this,SLOT(setCameraFromUI()));
    connect(m_ui->topCamera,SIGNAL(clicked()),this,SLOT(setCameraFromUI()));
    connect(m_ui->rightCamera,SIGNAL(clicked()),this,SLOT(setCameraFromUI()));
    connect(m_ui->defaultBackCamera,SIGNAL(clicked()),this,SLOT(setCameraFromUI()));
    connect(m_ui->freeCam,SIGNAL(stateChanged(int)),this,SLOT(setFreeCamFlagFromUI(int)));
    m_ui->m_progressBar->setVisible(false);
    m_ui->loading->setVisible(false);
    m_ui->cameraBox->setDisabled(true);
    ColorHigh = QString (
                    "QProgressBar::chunk {"
                    "background-color: #11E615;"
                     "}");
    ColorHigh.append("QProgressBar {"
                  "border: 1px solid grey;"
                  "border-radius: 5px;"
                  "text-align: center;"
                  "background: #eeeeee;"
                  "}");
    ColorIntermediate = QString (
                    "QProgressBar::chunk {"
                    "background-color: #F3FF02;"
                     "}");
    ColorIntermediate.append("QProgressBar {"
                  "border: 1px solid grey;"
                  "border-radius: 5px;"
                  "text-align: center;"
                  "background: #eeeeee;"
                  "}");
    ColorLow = QString (
                    "QProgressBar::chunk {"
                    "background-color: #FF0217;"
                     "}");
    ColorLow.append("QProgressBar {"
                  "border: 1px solid grey;"
                  "border-radius: 5px;"
                  "text-align: center;"
                  "background: #eeeeee;"
                  "}");
    QIcon left_cam = QIcon(QString("textures/camera_lt.jpg"));
    QIcon right_cam = QIcon(QString("textures/camera_rt.jpg"));
    QIcon top_cam = QIcon(QString("textures/camera_top.jpg"));
    QIcon back_cam = QIcon(QString("textures/camera_back.jpg"));
    m_ui->leftCamera->setIcon(left_cam);
    m_ui->leftCamera->setIconSize(QSize(40,40));
    m_ui->rightCamera->setIcon(right_cam);
    m_ui->rightCamera->setIconSize(QSize(40,40));
    m_ui->topCamera->setIcon(top_cam);
    m_ui->topCamera->setIconSize(QSize(40,40));
    m_ui->defaultBackCamera->setIcon(back_cam);
    m_ui->defaultBackCamera->setIconSize(QSize(40,40));
    m_ui->grenadePower->setStyleSheet(ColorHigh);
    m_ui->powerBar->setStyleSheet(ColorLow);
    m_ui->inGameBarsDisplay->setVisible(false);
    m_settingWind = 0;
    m_updateScore = 0;
    movieLeft = new QMovie("textures/glowingarrowleft.gif");
    movieRight = new QMovie("textures/glowingarrowright.gif");
    m_ui->windDirRtArrow->setMovie(movieRight);
    m_ui->windDirLtArrow->setMovie(movieLeft);
    QLCDNumber *lcd = m_ui->windNumber;
    lcd->setSegmentStyle( QLCDNumber::Filled );
    QPalette palette = lcd->palette();
    palette.setColor(QPalette::Normal, QPalette::Background,  Qt::black);
    palette.setColor(QPalette::Normal, QPalette::Light, Qt::red);
    lcd->setPalette(palette);
    m_ui->inGameBarsDisplay->setVisible(false);
}
GameControls::~GameControls ()
dtor
Definition at line 117 of file GameControls.cpp.
References m_ui.
{
    // no need to do anything at present
    delete m_ui;
}
Member Function Documentation
void GameControls::constructTheGame () [private]
construct the gl(GameLogic) window
Definition at line 423 of file GameControls.cpp.
References m_gl.
{
    if(!m_gl)
    {
        m_gl = new GameLogic(this);
    }
    else
    {
        std::cout<<"means game world already created";
    }
}
float GameControls::getCurrentScore () [private]
get the current score
Definition at line 414 of file GameControls.cpp.
References GameLogic::getCurrentGrenadeLife(), and m_gl.
{
    if (m_gl)
    {
        return m_gl->getCurrentGrenadeLife();
    }
}
void GameControls::keyPressEvent (QKeyEvent * _event) [protected]
override the keyPressEvent inherited from QObject so we can handle key presses.
Parameters:
[in] _event the event to process
Definition at line 138 of file GameControls.cpp.
References GameLogic::getGameLostFlag(), GameLogic::getGameWonFlag(), GameLogic::getSimulationFlag(), m_gl, GameLogic::processKeyDown(), and setPowerBar().
{
  // this method is called every time the main window recives a key event.
  // we then switch on the key value and set the camera in the GLWindow
    if ((m_gl != NULL) && (m_gl->getGameWonFlag() == false) && (m_gl->getGameLostFlag() == false))
    {
        if(m_gl->getSimulationFlag() == 0)
        {
            switch (_event->key())
            {
                case Qt::Key_Escape : QApplication::exit(EXIT_SUCCESS); break;
                case Qt::Key_F : showFullScreen(); break;
                case Qt::Key_N : showNormal(); break;
                case Qt::Key_Up : setPowerBar(10); break;
                case Qt::Key_Down : setPowerBar(-10); break;
                case Qt::Key_Space : setPowerBar(0);  break;
                default : break;
        }
        m_gl->processKeyDown(_event);
        }
    }// block all keys if we are in air
}
void GameControls::keyReleaseEvent (QKeyEvent * _event) [protected]
Definition at line 125 of file GameControls.cpp.
References GameLogic::getGameLostFlag(), GameLogic::getGameWonFlag(), m_gl, and GameLogic::processKeyUp().
{
    // once we have processed any key here pass the event
    // onto the GLWindow class to do more processing
    if((m_gl != NULL) && (m_gl->getGameWonFlag() == false) && (m_gl->getGameLostFlag() == false))
    {
        m_gl->processKeyUp(_event);
    }
}
void GameControls::resetGame () [private, slot]
reset game slot
Definition at line 341 of file GameControls.cpp.
References m_gameRunning, m_gl, m_settingWind, m_ui, m_updateScore, and GameLogic::~GameLogic().
{
    if(m_gl)
    {
        m_ui->s_GameWindowLayout->removeWidget(m_gl);
        m_gl->~GameLogic();
        killTimer(m_gameRunning);
        killTimer(m_settingWind);
        killTimer(m_updateScore);
        m_gl = 0;
    }
    m_ui->m_startGame->setDisabled(false);
    m_ui->levelSettingsBox->setDisabled(false);
    m_ui->textBrowser->clearFocus();
    m_ui->inGameBarsDisplay->setVisible(false);
    m_ui->cameraBox->setDisabled(true);
}
void GameControls::setAdvancedDifficulty () [private, slot]
difficulty advanced radio
Definition at line 224 of file GameControls.cpp.
References ADVANCED, m_gl, and GameLogic::setDifficulty().
{
    m_gl->setDifficulty(ADVANCED);
}
void GameControls::setBeginnerDifficulty () [private, slot]
difficulty beginner radio
Definition at line 218 of file GameControls.cpp.
References BEGINNER, m_gl, and GameLogic::setDifficulty().
{
    // can do some processing if we want here later,else connect signal directly using m_gl,setDifficulty at the top in this code
    m_gl->setDifficulty(BEGINNER);
}
void GameControls::setCameraFromUI () [private, slot]
to set the current selected camera
Definition at line 438 of file GameControls.cpp.
References CAM_DEFAULT, CAM_LEFT, CAM_RIGHT, CAM_TOP, GameLogic::changeCamera(), m_gl, and m_ui.
{
    if (QObject::sender() == m_ui->leftCamera)
    {
        m_gl->changeCamera(CAM_LEFT);
    }
    else if (QObject::sender() == m_ui->topCamera)
    {
         m_gl->changeCamera(CAM_TOP);
    }
    else if (QObject::sender() == m_ui->rightCamera)
    {
         m_gl->changeCamera(CAM_RIGHT);
    }
    else if (QObject::sender() == m_ui->defaultBackCamera)
    {
         m_gl->changeCamera(CAM_DEFAULT);
    }
}
void GameControls::setFreeCamFlagFromUI (int _freeCamFlag) [private, slot]
to detach the camera
Definition at line 463 of file GameControls.cpp.
References m_gl, and GameLogic::setFreeCamFlag().
 {
     if(m_gl)
     {
         m_gl->setFreeCamFlag(_freeCamFlag);
     }
 }
void GameControls::setLevelDisplay (int _levelDisplay) [private, slot]
level number display
Definition at line 229 of file GameControls.cpp.
References m_ui.
{
    QString level = "LEVEL->>>>";
    m_ui->m_levelLabel->setText(level + QString::number(_levelDisplay));
}
void GameControls::setPowerBar (float _inputPower) [private]
sets the power bar to reflect the power applied to the grenade
Parameters:
[in] _inputPower to be set
Definition at line 235 of file GameControls.cpp.
References ColorHigh, ColorIntermediate, ColorLow, and m_ui.
{
    static float _accumulatedPower = 0; // staitic as one time initialization fo power enough, its not aproperty of controls, so cant be its member
    if(_inputPower != 0)
    {
        _accumulatedPower = _accumulatedPower + _inputPower;
        if(_accumulatedPower >= 40)
        {
            _accumulatedPower = 40;
        }
        else if (_accumulatedPower <= 0)
        {
            _accumulatedPower = 0;
        }
     }
    else if (_inputPower == 0) // for down arrow to reduce power
    {
        _accumulatedPower = 0;
    }
    if (_accumulatedPower <= 20)
    {
       m_ui->powerBar->setStyleSheet(ColorHigh);
    }
    else if (_accumulatedPower > 20 && _accumulatedPower <= 30)
    {
       m_ui->powerBar->setStyleSheet(ColorIntermediate);
    }
    else if (_accumulatedPower > 30)
    {
        m_ui->powerBar->setStyleSheet(ColorLow);
    }
    m_ui->powerBar->setValue(_accumulatedPower);
}
void GameControls::setProgressBar () [private]
sets the progress bar to reflect the loading progress
Definition at line 276 of file GameControls.cpp.
References GameLogic::getGameStartedFlag(), m_gameRunning, m_gl, and m_ui.
{
    if ( m_gl && m_gl->getGameStartedFlag() == 1)
    {
        m_ui->m_progressBar->setValue(m_ui->m_progressBar->maximum());
        m_ui->m_progressBar->setVisible(false);
        m_ui->loading->setVisible(false);
        killTimer(m_gameRunning);
    }
    else
    {
        m_ui->m_progressBar->setValue(10);
    }
}
void GameControls::setRandomValueForWindLevel3 () [private]
sets the wind value got from gamelogic to reflect on the ui
Definition at line 368 of file GameControls.cpp.
References GameLogic::getSimulationFlag(), m_gl, m_ui, movieLeft, movieRight, and GameLogic::setWindValue().
{
    static int seedValue = 10; // again common value, cannot be a member of this class
    static int valueGenerated = 0;
    int windValue = 0;
    if(m_gl)
    {
        if((m_gl->getSimulationFlag() == 0) && (valueGenerated == 0))
        {
            ngl::Random *randObj = ngl::Random::instance();
            windValue = (int)randObj->randomNumber(seedValue);
            m_gl->setWindValue(windValue);
            if (windValue > 0)
            {
                // set the label value to display wind
                m_ui->windNumber->display(windValue);
                movieRight->setPaused(true);
                movieLeft->setPaused(false);
            }
            else
            {
                m_ui->windNumber->display(windValue);
                movieLeft->setPaused(true);
                movieRight->setPaused(false);
            }
            valueGenerated = 1;
         }
        else if (m_gl->getSimulationFlag() == 1)
        {
            valueGenerated = 0;
        }
   }
}
void GameControls::startGame () [private, slot]
start game slot
Definition at line 172 of file GameControls.cpp.
References ADVANCED, BEGINNER, constructTheGame(), m_gameRunning, m_gl, m_settingWind, m_ui, m_updateScore, movieLeft, movieRight, GameLogic::setDifficulty(), GameLogic::setLevel(), and setProgressBar().
{
    m_ui->m_progressBar->setVisible(true);
    m_ui->loading->setVisible(true);
    m_gameRunning = startTimer(1);
    setProgressBar();
    constructTheGame();
    if ( m_ui->m_beginner->isChecked())
    {
        m_gl->setDifficulty(BEGINNER);
    }
    else if(m_ui->m_advanced->isChecked())
    {
        m_gl->setDifficulty(ADVANCED);
    }
    m_gl->setLevel(m_ui->m_levelSetDial->value());
    m_ui->s_GameWindowLayout->addWidget(m_gl,0,0,1,8);
    m_ui->m_startGame->setDisabled(true);
    m_ui->levelSettingsBox->setDisabled(true);
    m_ui->textBrowser->clearFocus();
    m_ui->inGameBarsDisplay->setVisible(true);
    m_ui->cameraBox->setDisabled(false);
    m_ui->windDirRtArrow->setDisabled(true);
    m_ui->windDirLtArrow->setDisabled(true);
    m_ui->windNumber->setDisabled(true);
    m_ui->windText->setDisabled(true);
    if(m_ui->m_levelSetDial->value() >= 2)
    {
        m_settingWind = startTimer(2);
        m_ui->windDirRtArrow->setDisabled(false);
        m_ui->windDirLtArrow->setDisabled(false);
        m_ui->windNumber->setDisabled(false);
        m_ui->windText->setDisabled(false);
        movieLeft->start();
        movieRight->start();
        movieLeft->setPaused(true);
        movieRight->setPaused(true);
    }
    m_updateScore = startTimer(5);
}
void GameControls::timerEvent (QTimerEvent * _event) [private]
timerEvent to process the elapsed timers
Parameters:
[in] _event the timer event to process
Definition at line 294 of file GameControls.cpp.
References ColorIntermediate, ColorLow, getCurrentScore(), GameLogic::getGameWonFlag(), m_gameRunning, m_gl, m_settingWind, m_ui, m_updateScore, GameLogic::setGameLostFlag(), setProgressBar(), and setRandomValueForWindLevel3().
{
    if (_event->timerId() == m_gameRunning)
    {
        setProgressBar();
    }
    if (_event->timerId() == m_settingWind)
    {
        setRandomValueForWindLevel3();
    }
    if (_event->timerId() == m_updateScore)
    {
        // only if the game has not been won, should we update the score..so this might save us some function calls after the player has collided with the goal
        if (m_gl->getGameWonFlag() == true)
        {
            // display Text on the window
            m_ui->inGameBarsDisplay->setVisible(false);
            killTimer(m_updateScore);
        }
        else
        {
            float tempScore = getCurrentScore();
            if (tempScore <= 50 && tempScore > 25)
            {
                m_ui->grenadePower->setStyleSheet(ColorIntermediate);
            }
            else if (tempScore <= 25)
            {
                m_ui->grenadePower->setStyleSheet(ColorLow);
            }
            m_ui->grenadePower->setValue(tempScore);
       // also check if its 0, if so, the player has lost and this has to be informed and the timer killed
           if ( tempScore == 0)
           {
                m_gl->setGameLostFlag();
                m_ui->inGameBarsDisplay->setVisible(false);
                killTimer(m_updateScore);
           }
       }
   }
}
Member Data Documentation
QString GameControls::ColorHigh [private]
color style sheets to change the ui poer bars and score bars based on the current score
Definition at line 86 of file GameControls.h.
QString GameControls::ColorIntermediate [private]
Definition at line 86 of file GameControls.h.
QString GameControls::ColorLow [private]
Definition at line 86 of file GameControls.h.
int GameControls::isStartButtonClicked [private]
to signal if the start button is clicked
Definition at line 82 of file GameControls.h.
int GameControls::m_gameRunning [private]
timer to set after the game starts running, used to hide loading page
Definition at line 70 of file GameControls.h.
GameLogic* GameControls::m_gl [private]
our gl window created in GameLogic.h
Definition at line 62 of file GameControls.h.
int GameControls::m_settingWind [private]
timer to set wind speed
Definition at line 74 of file GameControls.h.
Ui::GameControls* GameControls::m_ui [private]
our ui namespace
Definition at line 66 of file GameControls.h.
int GameControls::m_updateScore [private]
timer to update the score after querying the GameLogic class
Definition at line 78 of file GameControls.h.
QMovie* GameControls::movieLeft [private]
gif animations to display wind arrow marks
Definition at line 90 of file GameControls.h.
QMovie * GameControls::movieRight [private]
Definition at line 90 of file GameControls.h.
The documentation for this class was generated from the following files:
GameControls.h
GameControls.cpp