GRENADE GAME: GamePhysicsEngine Class Reference
GamePhysicsEngine Class Reference
GamePhysicsEngine class is the bullet physics engine class handling the players and obstacle movements and detecting collisions and applying impulse and gravity on the models.
#include <GamePhysicsEngine.h>
Public Member Functions
GamePhysicsEngine ()
def ctor
virtual ~GamePhysicsEngine ()
virtual dtor
void getMeshFromObj (ngl::Obj *_m)
gets triangulated mesh from obj
void step ()
step simulation module
void addGround (const ngl::Vec3 &_pos)
static ground plane
void addBox (const ngl::Vec3 &_pos, ngl::Vec4 _scale, boundingExtras _inputRbodyType)
box shaped coll box for ammunition
void addSkyBox (const ngl::Vec3 &_pos, ngl::Vec4 _bounds)
add sky box
void moveBox (int _bodyreference, float _inputimpulse)
used in level3 to move tanks
void addConvexGrenade (const ngl::Vec3 &_pos)
add our convex player
void addConvexStones (const ngl::Vec3 &_pos, const ngl::Vec3 &_rot)
add our convex tank
void moveGrenade (int, int _inputUpDownAccumulated, int _inputWindValue=0)
add impulse to player
void senseCollision ()
sense the collison using continuous collision detection
int getCollisionShape (unsigned int _index) const
gets a particular collision shape
ngl::Mat4 getTransformMatrix (unsigned int _index)
gets a transformation matrix
ngl::Vec3 getPosition (unsigned int _index)
gets a particular position
unsigned int getNumCollisionObjects () const
gets total number of collision objects
bool getSimulationFlag ()
gets the simulation flag
void setGrenadeObstacleCcount (int _noOfLives)
sets the grenade obstacle count value used for scoring
float getGrenadeObstacleCcount ()
gets the obstacle count value used for scoring
bool getGameWonFlag ()
get the game won flag if grenade hits the ammunition
Private Member Functions
void setGameWonFlag ()
sets the game won flag when grande hits amunition box
Private Attributes
bool doingSimulationInAir
flag to indicate simulation
std::map< std::string,
collisionMesh * > m_collisionData
collision repository
ngl::Obj * tempObj
temp obj mesh
void * boxptr
pointer to determine the collison shape
void * wallptr
pointer to determine the collison shape
void * grenadeptr
pointer to determine the collison shape
void * obstacleptr
pointer to determine the collison shape
int grenadeObstacleCcount
pointer to determine the collison shape
bool gameWonFlag
game won flag when grenade hits ammunition
btAlignedObjectArray
< btCollisionShape * > m_collisionShapes
standard bullet variables to store collison shapes, the broadphase filter, the dispatcher, the constraint solver, defaut collision config, the discrete world, triangulated mesh, static plane
btBroadphaseInterface * m_broadphase
btCollisionDispatcher * m_dispatcher
btConstraintSolver * m_solver
btDefaultCollisionConfiguration * m_collisionConfiguration
btDiscreteDynamicsWorld * m_dynamicsWorld
btTriangleMesh * mesh
btBvhTriangleMeshShape * meshShape
btStaticPlaneShape * planeShape
Detailed Description
GamePhysicsEngine class is the bullet physics engine class handling the players and obstacle movements and detecting collisions and applying impulse and gravity on the models.
Definition at line 45 of file GamePhysicsEngine.h.
Constructor & Destructor Documentation
GamePhysicsEngine::GamePhysicsEngine ()
def ctor
the default constraint solver. For parallel processing you can use a different solver (see Extras/BulletMultiThreaded)
Definition at line 22 of file GamePhysicsEngine.cpp.
References doingSimulationInAir, gameWonFlag, grenadeObstacleCcount, m_broadphase, m_collisionConfiguration, m_dispatcher, m_dynamicsWorld, and m_solver.
{
    std::cout<<"came in bullet engine......\n\n\n\n";
    doingSimulationInAir = 0;
    m_collisionConfiguration = new btDefaultCollisionConfiguration();
    m_dispatcher = new btCollisionDispatcher(m_collisionConfiguration);
    m_broadphase = new btDbvtBroadphase();
    btSequentialImpulseConstraintSolver* sol = new btSequentialImpulseConstraintSolver;
    m_solver = sol;
    m_dynamicsWorld = new btDiscreteDynamicsWorld(m_dispatcher,m_broadphase,m_solver,m_collisionConfiguration);
    m_dynamicsWorld->getSolverInfo().m_solverMode = SOLVER_USE_WARMSTARTING + SOLVER_SIMD;
    m_dynamicsWorld->setGravity(btVector3(0,-10,0));
    grenadeObstacleCcount = 0; // initial life of the grenade will be set from game logic
    gameWonFlag = false;
}
GamePhysicsEngine::~GamePhysicsEngine () [virtual]
virtual dtor
Definition at line 43 of file GamePhysicsEngine.cpp.
References m_broadphase, m_collisionConfiguration, m_collisionShapes, m_dispatcher, m_dynamicsWorld, and m_solver.
{
    //cleanup in the reverse order of creation/initialization
    //remove the rigidbodies from the dynamics world and delete them
    int i;
    for (i=m_dynamicsWorld->getNumCollisionObjects()-1; i>=0 ;i--)
    {
        btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[i];
        btRigidBody* body = btRigidBody::upcast(obj);
        if (body && body->getMotionState())
        {
            delete body->getMotionState();
        }
        m_dynamicsWorld->removeCollisionObject( obj );
        delete obj;
    }
    //delete collision shapes
    for (int j=0;j<m_collisionShapes.size();j++)
    {
        btCollisionShape* shape = m_collisionShapes[j];
        delete shape;
    }
    m_collisionShapes.clear();
    delete m_dynamicsWorld;
    delete m_solver;
    delete m_broadphase;
    delete m_dispatcher;
    delete m_collisionConfiguration;
}
Member Function Documentation
void GamePhysicsEngine::addBox (const ngl::Vec3 & _pos, ngl::Vec4 _scale, boundingExtras _inputRbodyType)
box shaped coll box for ammunition
Create Dynamic Objects
Definition at line 199 of file GamePhysicsEngine.cpp.
References boxptr, CRATE_AMMUNITION, friction, INVISIBLE_CAM_WALL, INVISIBLE_WALL, m_collisionShapes, m_dynamicsWorld, and wallptr.
{
    //create a dynamic rigidbody
    btCollisionShape* colShape;
    // this condition might look redundant, but this is needed to differentiate bewtween similar collision shapes by setting our own pointer into the collision shape depending on the object
    if (_inputRbodyType == CRATE_AMMUNITION)
    {
       colShape  = new btBoxShape(btVector3(_scale.m_x,_scale.m_y,_scale.m_z));
        boxptr = this;
    }
    else if (_inputRbodyType == INVISIBLE_WALL)
    {
        colShape = new btBoxShape(btVector3(_scale.m_x,_scale.m_y,_scale.m_z));
         wallptr = 0;
    }
    else if (_inputRbodyType == INVISIBLE_CAM_WALL)
    {
        colShape = new btBoxShape(btVector3(_scale.m_x,_scale.m_y,_scale.m_z));
         wallptr = 0;
    }
    //btCollisionShape* colShape = new  btCapsuleShape(0.5,1.0);//  btBoxShape(btVector3(_rad/2.0,_rad/2.0,_rad/2.0));
    m_collisionShapes.push_back(colShape);
    btTransform startTransform;
    startTransform.setIdentity();
    btScalar  mass(10.f);
    btVector3 localInertia(0,0,0);
    colShape->calculateLocalInertia(mass,localInertia);
    startTransform.setOrigin(btVector3(_pos.m_x,_pos.m_y,_pos.m_z));
    //using motionstate is recommended, it provides interpolation capabilities, and only synchronizes 'active' objects
    btDefaultMotionState* myMotionState = new btDefaultMotionState(startTransform);
    btRigidBody::btRigidBodyConstructionInfo rbInfo(mass,myMotionState,colShape,localInertia);
    rbInfo.m_restitution = 0.8f;
    rbInfo.m_friction = 100.5f;
    rbInfo.m_additionalAngularDampingFactor=4.0;
    rbInfo.m_additionalDamping=5.0;
    btRigidBody* body = new btRigidBody(rbInfo);
    body->setFriction(friction);
    //body->setActivationState(ISLAND_SLEEPING);
    body->setLinearFactor(btVector3(1,0,1));
    body->setAngularFactor(btVector3(0,1,0));
    if (_inputRbodyType == CRATE_AMMUNITION)
    {
        body->setUserPointer(boxptr);
    }
    else if (_inputRbodyType == INVISIBLE_WALL)
    {
        body->setUserPointer(wallptr);
    }
    body->setCollisionFlags(btCollisionObject::CF_STATIC_OBJECT);
    m_dynamicsWorld->addRigidBody(body);
}
void GamePhysicsEngine::addConvexGrenade (const ngl::Vec3 & _pos)
add our convex player
Create Dynamic Objects
Definition at line 320 of file GamePhysicsEngine.cpp.
References friction, getMeshFromObj(), grenadeptr, m_collisionShapes, m_dynamicsWorld, mesh, and tempObj.
{
        tempObj = new ngl::Obj("models/Grenade.obj","textures/Grenade.tga");
        getMeshFromObj(tempObj);
        grenadeptr = (this + 1);
        btConvexShape* tmpConvexShape = new btConvexTriangleMeshShape(mesh);
        std::cout<<"reducing vertices by creating a convex hull\n";
        //create a hull approximation
        btShapeHull* hull = new btShapeHull(tmpConvexShape);
        btScalar margin = tmpConvexShape->getMargin();
        hull->buildHull(margin);
        btConvexHullShape* simplifiedConvexShape = new btConvexHullShape((btScalar*)hull->getVertexPointer(),hull->numVertices());
        std::cout<<"new numTriangles = "<< hull->numTriangles();
        std::cout<<"new numIndices = "<<hull->numIndices();
        std::cout<<"new numVertices = "<< hull->numVertices();
        m_collisionShapes.push_back(simplifiedConvexShape);
        btTransform startTransform;
        startTransform.setIdentity();
        btScalar  mass(3.f);
        btVector3 localInertia(0,0,0);
        simplifiedConvexShape->calculateLocalInertia(mass,localInertia);
        startTransform.setOrigin(btVector3(_pos.m_x,_pos.m_y,_pos.m_z));
        //using motionstate is recommended, it provides interpolation capabilities, and only synchronizes 'active' objects
        btDefaultMotionState* myMotionState = new btDefaultMotionState(startTransform);
        btRigidBody::btRigidBodyConstructionInfo rbInfo(mass,myMotionState,simplifiedConvexShape,localInertia);
        rbInfo.m_restitution = 0.8f;
        rbInfo.m_friction = 100.5f;
        rbInfo.m_additionalAngularDampingFactor=4.0;
        rbInfo.m_additionalDamping=5.0;
        btRigidBody* body = new btRigidBody(rbInfo);
        body->setFriction(friction);
        body->setActivationState(DISABLE_DEACTIVATION);
        body->setUserPointer(grenadeptr);
        std::cout<<"ptr is "<<body->getUserPointer();
        m_dynamicsWorld->addRigidBody(body);
}
void GamePhysicsEngine::addConvexStones (const ngl::Vec3 & _pos, const ngl::Vec3 & _rot)
add our convex tank
Definition at line 364 of file GamePhysicsEngine.cpp.
References friction, getMeshFromObj(), m_collisionShapes, m_dynamicsWorld, mesh, obstacleptr, and tempObj.
{
        tempObj = new ngl::Obj("models/truck.obj","textures/Grenade.tga");
        getMeshFromObj(tempObj);
        obstacleptr = (this + 2);
        btConvexShape* tmpConvexShape = new btConvexTriangleMeshShape(mesh);
        std::cout<<"reducing vertices by creating a convex hull\n";
        //create a hull approximation
        btShapeHull* hull = new btShapeHull(tmpConvexShape);
        btScalar margin = tmpConvexShape->getMargin();
        hull->buildHull(margin);
        btConvexHullShape* simplifiedConvexShape = new btConvexHullShape((btScalar*)hull->getVertexPointer(),hull->numVertices());
        std::cout<<"new numTriangles = "<< hull->numTriangles();
        std::cout<<"new numIndices = "<<hull->numIndices();
        std::cout<<"new numVertices = "<< hull->numVertices();
        m_collisionShapes.push_back(simplifiedConvexShape);
        btTransform startTransform;
        startTransform.setIdentity();
        btScalar  mass(10.f);
        btVector3 localInertia(0,0,0);
        simplifiedConvexShape->calculateLocalInertia(mass,localInertia);
        startTransform.setOrigin(btVector3(_pos.m_x,_pos.m_y,_pos.m_z));
        startTransform.setRotation(btQuaternion(0,1,0,_rot.m_y));
        //using motionstate is recommended, it provides interpolation capabilities, and only synchronizes 'active' objects
        btDefaultMotionState* myMotionState = new btDefaultMotionState(startTransform);
        btRigidBody::btRigidBodyConstructionInfo rbInfo(mass,myMotionState,simplifiedConvexShape,localInertia);
        rbInfo.m_restitution = 0.8f;
        rbInfo.m_friction = 100.5f;
        rbInfo.m_additionalAngularDampingFactor=4.0;
        rbInfo.m_additionalDamping=5.0;
        btRigidBody* body = new btRigidBody(rbInfo);
        body->setFriction(friction);
        body->setLinearFactor(btVector3(1,0,1));
        body->setAngularFactor(btVector3(0,1,0));
        body->setUserPointer(obstacleptr);
        std::cout<<"ptr is "<<body->getUserPointer();
        m_dynamicsWorld->addRigidBody(body);
}
void GamePhysicsEngine::addGround (const ngl::Vec3 & _pos)
static ground plane
Definition at line 120 of file GamePhysicsEngine.cpp.
References friction, m_collisionShapes, m_dynamicsWorld, and planeShape.
{
        //m_groundShape = new btBoxShape(btVector3(_size.m_x,_size.m_y, _size.m_z));
        planeShape = new btStaticPlaneShape(btVector3(0,1,0),_pos.m_y);
        m_collisionShapes.push_back(planeShape);
        btTransform groundTransform;
        groundTransform.setIdentity();
        {
             btScalar mass(0.);
             //rigidbody is dynamic if and only if mass is non zero, otherwise static
             bool isDynamic = (mass != 0.f);
             btVector3 localInertia(0,0,0);
             if (isDynamic)
                 planeShape->calculateLocalInertia(mass,localInertia);
             //using motionstate is recommended, it provides interpolation capabilities, and only synchronizes 'active' objects
             btDefaultMotionState* myMotionState = new btDefaultMotionState(groundTransform);
             btRigidBody::btRigidBodyConstructionInfo rbInfo(mass,myMotionState,planeShape,localInertia);
             btRigidBody* body = new btRigidBody(rbInfo);
             body->setFriction(friction);
             //add the body to the dynamics world
             m_dynamicsWorld->addRigidBody(body);
        }
}
void GamePhysicsEngine::addSkyBox (const ngl::Vec3 & _pos, ngl::Vec4 _bounds)
add sky box
Create Dynamic Objects
Definition at line 269 of file GamePhysicsEngine.cpp.
References friction, m_collisionShapes, and m_dynamicsWorld.
{
    //create a dynamic rigidbody
    btCollisionShape* colShape = new btBoxShape(btVector3(_bounds.m_x,_bounds.m_y,_bounds.m_z));
    m_collisionShapes.push_back(colShape);
    btTransform startTransform;
    startTransform.setIdentity();
    btScalar  mass(1.f);
    btVector3 localInertia(0,0,0);
    colShape->calculateLocalInertia(mass,localInertia);
    startTransform.setOrigin(btVector3(_pos.m_x,_pos.m_y,_pos.m_z));
    //using motionstate is recommended, it provides interpolation capabilities, and only synchronizes 'active' objects
    btDefaultMotionState* myMotionState = new btDefaultMotionState(startTransform);
    btRigidBody::btRigidBodyConstructionInfo rbInfo(mass,myMotionState,colShape,localInertia);
    rbInfo.m_restitution = 0.8f;
    rbInfo.m_friction = 100.5f;
    rbInfo.m_additionalAngularDampingFactor=4.0;
    rbInfo.m_additionalDamping=5.0;
    btRigidBody* body = new btRigidBody(rbInfo);
    body->setFriction(friction);
    body->setActivationState(ISLAND_SLEEPING);
    body->setCollisionFlags(btCollisionObject::CF_STATIC_OBJECT);
    m_dynamicsWorld->addRigidBody(body);
}
int GamePhysicsEngine::getCollisionShape (unsigned int _index) const
gets a particular collision shape
Parameters:
_index to get from
Definition at line 151 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld.
{
  btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[_index];
  btCollisionShape *collisionShape = obj->getCollisionShape();
  return collisionShape->getShapeType();
}
bool GamePhysicsEngine::getGameWonFlag ()
get the game won flag if grenade hits the ammunition
Definition at line 554 of file GamePhysicsEngine.cpp.
References gameWonFlag.
{
    return gameWonFlag;
}
float GamePhysicsEngine::getGrenadeObstacleCcount ()
gets the obstacle count value used for scoring
Definition at line 540 of file GamePhysicsEngine.cpp.
References grenadeObstacleCcount.
{
    return grenadeObstacleCcount;
}
void GamePhysicsEngine::getMeshFromObj (ngl::Obj * _m)
gets triangulated mesh from obj
Definition at line 85 of file GamePhysicsEngine.cpp.
References mesh, and meshShape.
{
    mesh = new btTriangleMesh(false);
    ngl::Vec3 vv,vv1,vv2;
    btVector3 bv1,bv2,bv3;
    std::vector<ngl::Face> faces=_m->getFaceList();
    unsigned int size1=faces.size();
    for(unsigned int i=0; i<size1; i++)
    {
        vv=_m->getVertexAtIndex(faces[i].m_vert[0]);
        vv1=_m->getVertexAtIndex(faces[i].m_vert[1]);
        vv2=_m->getVertexAtIndex(faces[i].m_vert[2]);
        bv1 = btVector3(btScalar(vv.m_x),btScalar(vv.m_y),btScalar(vv.m_z));
        bv2 = btVector3(btScalar(vv1.m_x),btScalar(vv1.m_y),btScalar(vv1.m_z));
        bv3 = btVector3(btScalar(vv2.m_x),btScalar(vv2.m_y),btScalar(vv2.m_z));
        mesh->addTriangle(bv1,bv2,bv3);
    }
    meshShape = new btBvhTriangleMeshShape(mesh,true,true);
}
unsigned int GamePhysicsEngine::getNumCollisionObjects () const [inline]
gets total number of collision objects
Definition at line 134 of file GamePhysicsEngine.h.
References m_dynamicsWorld.
{return m_dynamicsWorld->getNumCollisionObjects();}
ngl::Vec3 GamePhysicsEngine::getPosition (unsigned int _index)
gets a particular position
Parameters:
_index to get from
Definition at line 182 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld.
{
        btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[_index];
        btRigidBody* body = btRigidBody::upcast(obj);
        if (body && body->getMotionState())
        {
                btTransform trans;
                body->getMotionState()->getWorldTransform(trans);
                return ngl::Vec3(trans.getOrigin().getX(),
                                                                                 trans.getOrigin().getY(),
                                                                                 trans.getOrigin().getZ()
                                                                                );
        }
}
bool GamePhysicsEngine::getSimulationFlag ()
gets the simulation flag
Definition at line 519 of file GamePhysicsEngine.cpp.
References doingSimulationInAir.
{
  return doingSimulationInAir;
}
ngl::Mat4 GamePhysicsEngine::getTransformMatrix (unsigned int _index)
gets a transformation matrix
Parameters:
_index to get from
Definition at line 159 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld.
{
        btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[_index];
        btRigidBody* body = btRigidBody::upcast(obj);
        if (body && body->getMotionState())
        {
                btTransform trans;
                body->getMotionState()->getWorldTransform(trans);
                float matrix[16];
                trans.getOpenGLMatrix(matrix);
                return ngl::Mat4( matrix[0],matrix[1],matrix[2],matrix[3],
                                  matrix[4],matrix[5],matrix[6],matrix[7],
                                  matrix[8],matrix[9],matrix[10],matrix[11],
                                  matrix[12],matrix[13],matrix[14],matrix[15]
                                );
        }
}
void GamePhysicsEngine::moveBox (int _bodyreference, float _inputimpulse)
used in level3 to move tanks
Definition at line 301 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld.
{
    btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[_bodyreference];
    btRigidBody* body = btRigidBody::upcast(obj);
    body->setActivationState(ACTIVE_TAG);
    body->setGravity(btVector3(0,-10,0));
    if (body && body->getMotionState())
    {
            btTransform trans = body->getWorldTransform();
            trans.getOrigin() += (btVector3((_bodyreference * _inputimpulse),0, 0 ));
            trans.setRotation(trans.getRotation() + btQuaternion(0,1,0,(_bodyreference * _inputimpulse)));
            body->setWorldTransform(trans);
    }
}
void GamePhysicsEngine::moveGrenade (int _inputRightLeftAccumulated, int _inputUpDownAccumulated, int _inputWindValue = 0)
add impulse to player
Definition at line 417 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld.
{
    if (_inputUpDownAccumulated != 0)
    {
        btCollisionObject* obj = m_dynamicsWorld->getCollisionObjectArray()[0];
        btRigidBody* body = btRigidBody::upcast(obj);
        if (body && body->getMotionState())
        {
            btTransform trans = body->getWorldTransform();
            // if level3, get wind as input and set x of gravity to that input
            if (_inputWindValue != 0)
            {
            body->setGravity(btVector3((_inputWindValue),-10,0));
            }
              body->applyCentralImpulse(btVector3(_inputRightLeftAccumulated,_inputUpDownAccumulated,_inputUpDownAccumulated));
        }
    }
}
void GamePhysicsEngine::senseCollision ()
sense the collison using continuous collision detection
Definition at line 446 of file GamePhysicsEngine.cpp.
References boxptr, doingSimulationInAir, grenadeptr, m_dispatcher, obstacleptr, setGameWonFlag(), and setGrenadeObstacleCcount().
{
    int numContacts = 0;
    int numManifolds = m_dispatcher->getNumManifolds();
    //std::cout<<"number of Manifolds is "<<numManifolds<<std::endl;
    for (int i=0;i<numManifolds;i++)
    {
        btPersistentManifold* contactManifold = m_dispatcher->getManifoldByIndexInternal(i);
        btCollisionObject* obA = static_cast<btCollisionObject*>(contactManifold->getBody0());
        btCollisionObject* obB = static_cast<btCollisionObject*>(contactManifold->getBody1());
        numContacts = contactManifold->getNumContacts();
        if ((numContacts == 1) && (doingSimulationInAir == 1))
        {
            if((obA->getCollisionShape()->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE) && (obB->getCollisionShape()->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE))
            {
                if((obA->getUserPointer() == grenadeptr) && (obB->getUserPointer() == obstacleptr))
                {
                    std::cout<<"yesssss i hit youuuuuu....";
                    obA->setCollisionFlags(btCollisionObject::CF_NO_CONTACT_RESPONSE|btCollisionObject::CF_DISABLE_SPU_COLLISION_PROCESSING);
                    obB->setCollisionFlags(btCollisionObject::CF_DISABLE_SPU_COLLISION_PROCESSING);
                    setGrenadeObstacleCcount(0);
                    break; // this is reqd to exit, else, numcontacts remains as one for quite a while which will lead to deduction of lives more than once
                }
        }
        if((obA->getCollisionShape()->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE) && (obB->getCollisionShape()->getShapeType() == BOX_SHAPE_PROXYTYPE))
        {
            if((obA->getUserPointer() == grenadeptr) && (obB->getUserPointer() == boxptr))
            {
                std::cout<<"oh, yeah..you won...";
                setGameWonFlag();
                break;
            }
        }
    }
    if ((numContacts == 0) && (obA->getUserPointer() == grenadeptr) && (obA->getCollisionShape()->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE) && (obB->getCollisionShape()->getShapeType() == STATIC_PLANE_PROXYTYPE))
    {
      obA->setCollisionFlags(btCollisionObject::CF_DISABLE_SPU_COLLISION_PROCESSING);
      doingSimulationInAir = 1;
      //std::cout<<"doing simulation:\n"<<doingSimulationInAir;
    }
    else if((obA->getUserPointer() == grenadeptr) && (obA->getCollisionShape()->getShapeType() == CONVEX_HULL_SHAPE_PROXYTYPE) && (obB->getCollisionShape()->getShapeType() == STATIC_PLANE_PROXYTYPE))
    {
        obA->setCollisionFlags(btCollisionObject::CF_DISABLE_SPU_COLLISION_PROCESSING);
        doingSimulationInAir = 0;
     }
  }
  //std::cout<<"number of contacts is "<< numContacts<<std::endl;
}
void GamePhysicsEngine::setGameWonFlag () [private]
sets the game won flag when grande hits amunition box
Definition at line 548 of file GamePhysicsEngine.cpp.
References gameWonFlag.
{
    // a hit on the goal (crate box) has been detected, set the flag which will be queried by the game logic to let the user know that the game has been won
    gameWonFlag = true;
}
void GamePhysicsEngine::setGrenadeObstacleCcount (int _noOfLives)
sets the grenade obstacle count value used for scoring
Definition at line 525 of file GamePhysicsEngine.cpp.
References grenadeObstacleCcount.
{
    if(_noOfLives == 0)
    {
     grenadeObstacleCcount-=0.01;
    }
    else
    {
        grenadeObstacleCcount = _noOfLives;
    }
    std::cout<<"life of the grenade is "<<grenadeObstacleCcount;
}
void GamePhysicsEngine::step ()
step simulation module
Definition at line 111 of file GamePhysicsEngine.cpp.
References m_dynamicsWorld, and senseCollision().
{
    m_dynamicsWorld->stepSimulation(1.0/60.0,10);
    senseCollision();
}
Member Data Documentation
void* GamePhysicsEngine::boxptr [private]
pointer to determine the collison shape
Definition at line 181 of file GamePhysicsEngine.h.
bool GamePhysicsEngine::doingSimulationInAir [private]
flag to indicate simulation
Definition at line 165 of file GamePhysicsEngine.h.
bool GamePhysicsEngine::gameWonFlag [private]
game won flag when grenade hits ammunition
Definition at line 206 of file GamePhysicsEngine.h.
int GamePhysicsEngine::grenadeObstacleCcount [private]
pointer to determine the collison shape
Definition at line 201 of file GamePhysicsEngine.h.
void* GamePhysicsEngine::grenadeptr [private]
pointer to determine the collison shape
Definition at line 191 of file GamePhysicsEngine.h.
btBroadphaseInterface* GamePhysicsEngine::m_broadphase [private]
Definition at line 214 of file GamePhysicsEngine.h.
btDefaultCollisionConfiguration* GamePhysicsEngine::m_collisionConfiguration [private]
Definition at line 220 of file GamePhysicsEngine.h.
std::map<std::string,collisionMesh *> GamePhysicsEngine::m_collisionData [private]
collision repository
Definition at line 171 of file GamePhysicsEngine.h.
btAlignedObjectArray<btCollisionShape*> GamePhysicsEngine::m_collisionShapes [private]
standard bullet variables to store collison shapes, the broadphase filter, the dispatcher, the constraint solver, defaut collision config, the discrete world, triangulated mesh, static plane
Definition at line 212 of file GamePhysicsEngine.h.
btCollisionDispatcher* GamePhysicsEngine::m_dispatcher [private]
Definition at line 216 of file GamePhysicsEngine.h.
btDiscreteDynamicsWorld* GamePhysicsEngine::m_dynamicsWorld [private]
Definition at line 222 of file GamePhysicsEngine.h.
btConstraintSolver* GamePhysicsEngine::m_solver [private]
Definition at line 218 of file GamePhysicsEngine.h.
btTriangleMesh* GamePhysicsEngine::mesh [private]
Definition at line 224 of file GamePhysicsEngine.h.
btBvhTriangleMeshShape* GamePhysicsEngine::meshShape [private]
Definition at line 226 of file GamePhysicsEngine.h.
void* GamePhysicsEngine::obstacleptr [private]
pointer to determine the collison shape
Definition at line 196 of file GamePhysicsEngine.h.
btStaticPlaneShape* GamePhysicsEngine::planeShape [private]
Definition at line 228 of file GamePhysicsEngine.h.
ngl::Obj* GamePhysicsEngine::tempObj [private]
temp obj mesh
Definition at line 176 of file GamePhysicsEngine.h.
void* GamePhysicsEngine::wallptr [private]
pointer to determine the collison shape
Definition at line 186 of file GamePhysicsEngine.h.
The documentation for this class was generated from the following files:
GamePhysicsEngine.h
GamePhysicsEngine.cpp