GRENADE GAME: GameLevel Class Reference
GameLevel Class Reference
GameLevel class handles various things related to the level of the game world from creating the level/all the mesh data and models,loading the corresponsing transform stack and also interacts with the physics engine to add/retrieve the collision boxes to/from our models.
#include <GameLevel.h>
Public Member Functions
GameLevel ()
GameLevel (GameDrawEngine *_inputDrawEngine, GamePhysicsEngine *_inputPhysicsEngine, int _inputScreenHeight=1024, int _inputScreenWidth=780)
ctor to create GameLevel
~GameLevel ()
void addPlayerToLevel ()
add the grenade mesh to level
void addObstaclesToLevel ()
add the obstacle mesh to level
void addCrateBoxToLevel ()
add the cratebox mesh to level
void addBGToLevel ()
add the sky and grass mesh to level
void addCollisionBoxes ()
add the bullet collision boxes for all models
void drawLevel ()
draw the level
void setLevelCam (ngl::Camera *_cam)
set the level camera
void setLevelDifficulty (DIFFICULTY_LEVELS _difficulty)
creates the specified model
GameModel * getPlayer ()
get reference to player
GAME_LEVELS getLevelNumber ()
get the level number
void setLevelNumber (GAME_LEVELS _inputLevelNumber)
set the level number
void simulateAI ()
move models randomly for level 3
void moveGrenade ()
move grenade oveloaded function to include wind factor
void moveGrenade (int)
void moveObstacles ()
move obstacles
void setArrowDrawFlag (int _inputKey)
set the arrow direction arrow draw flag
void accumulateDirection (int _inputdir)
keep accumulating direction
void accumulateAcceleration (int _inputAcceleration)
keep accumulating acceleration
void addGraphicImages ()
add graphic images such as the bounding bunkers and the direction arrows
float getAccumulatedDirection ()
get accumulated direction
void setFreeCamFlag (int _inputFreeCamFlag)
set the free cam flag
Protected Attributes
std::map< int, GameModel * > m_modelRepos
model repository with enum key
std::map< int, GameModel * > m_graphicRepos
graphic image repository with enum key
Private Member Functions
void loadModelsWithoutBulletTransformations (ngl::TransformStack _transformStack, const ngl::Vec3 &_pos, const ngl::Vec4 &_rot, const ngl::Vec4 &_scale)
load the models which does not have anything to do with bullet using its own transform stack
void drawExtras ()
draw module to draw all the extras such as graphic images and anti bullet objs
Private Attributes
int _screenHeight
screen ht
int _screenWidth
screen wdth
int _numberOfObstacles
_total number of obstacles
DIFFICULTY_LEVELS m_difficulty
enum difficulty levels
GAME_LEVELS m_levelNumber
current level number
GameModel * _player
player pointer
GameDrawEngine * _drawEngine
drawing engine
GamePhysicsEngine * _physicsEngine
model repository with enum key
ngl::TransformStack m_transformStack
transform stack of the corresponding model
int arrowDraw
flag to check whether to draw the arrow/ not drawn during simulation
int accumulatedDirection
total accumulated direction from the user keypress
int accumulatedAcceleration
total accumulated acceleration from the user keypress
int m_freeCamFlag
flag to check if free cam is enabled/disabled
Detailed Description
GameLevel class handles various things related to the level of the game world from creating the level/all the mesh data and models,loading the corresponsing transform stack and also interacts with the physics engine to add/retrieve the collision boxes to/from our models.
Definition at line 40 of file GameLevel.h.
Constructor & Destructor Documentation
GameLevel::GameLevel ()
Definition at line 7 of file GameLevel.cpp.
References _drawEngine, _physicsEngine, _player, _screenHeight, _screenWidth, accumulatedAcceleration, accumulatedDirection, arrowDraw, BEGINNER, m_difficulty, and m_freeCamFlag.
{
    _drawEngine = 0;
    _physicsEngine = 0;
    _screenHeight = 0;
    _screenWidth = 0;
    _player = 0;
    m_difficulty = BEGINNER;
    accumulatedDirection = 0;
    accumulatedAcceleration = 0;
    arrowDraw = 1;
    m_freeCamFlag = 0;
    ngl::VAOPrimitives *prim = ngl::VAOPrimitives::instance();
    prim->createLineGrid("plane",140,140,80);
}
GameLevel::GameLevel (GameDrawEngine * _inputDrawEngine, GamePhysicsEngine * _inputPhysicsEngine, int _inputScreenHeight = 1024, int _inputScreenWidth = 780)
ctor to create GameLevel
Definition at line 23 of file GameLevel.cpp.
References _drawEngine, _physicsEngine, _player, _screenHeight, _screenWidth, accumulatedAcceleration, accumulatedDirection, arrowDraw, BEGINNER, m_difficulty, and m_freeCamFlag.
{
    _drawEngine = _inputDrawEngine;
    _physicsEngine = _inputPhysicsEngine;
    _screenHeight = _inputScreenHeight;
    _screenWidth = _inputScreenWidth;
    _player = 0;
    m_difficulty = BEGINNER;
    accumulatedDirection = 0;
    accumulatedAcceleration = 0;
    arrowDraw = 1;
    m_freeCamFlag = 0;
}
GameLevel::~GameLevel ()
Definition at line 476 of file GameLevel.cpp.
{
}
Member Function Documentation
void GameLevel::accumulateAcceleration (int _inputAcceleration)
keep accumulating acceleration
Parameters:
[in] _inputAcceleration new direction
Definition at line 337 of file GameLevel.cpp.
References accumulatedAcceleration.
{
    if(_inputAcceleration != 0)
    {
        accumulatedAcceleration = accumulatedAcceleration + _inputAcceleration;
        if(accumulatedAcceleration >= 40)
        {
            accumulatedAcceleration = 40;
        }
        else if (accumulatedAcceleration <= 0)
        {
            accumulatedAcceleration = 0;
        }
    }
    else if (_inputAcceleration == 0) // for down arrow to reduce power
    {
        accumulatedAcceleration = 0;
    }
}
void GameLevel::accumulateDirection (int _inputdir)
keep accumulating direction
Parameters:
[in] _inputdir new direction
Definition at line 306 of file GameLevel.cpp.
References _physicsEngine, accumulatedDirection, DIRECTION_ARROW, GamePhysicsEngine::getTransformMatrix(), and m_graphicRepos.
{
    ngl::Transformation trans;
    trans.setMatrix(_physicsEngine->getTransformMatrix(0));
    if(_inputdir != 0)
    {
        accumulatedDirection = accumulatedDirection + _inputdir;
        if(accumulatedDirection > 90)
        {
            accumulatedDirection = 90;
        }
        else if (accumulatedDirection < -90)
        {
            accumulatedDirection = -90;
        }
    m_graphicRepos[DIRECTION_ARROW]->setRotation(ngl::Vec4(0,accumulatedDirection,0,1));
    }
    else if (_inputdir == 0)
    {
        m_graphicRepos[DIRECTION_ARROW]->setRotation(ngl::Vec4(0,0,0,1));
    }
}
void GameLevel::addBGToLevel ()
add the sky and grass mesh to level
Definition at line 180 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, m_modelRepos, MODEL_BGS, and MODEL_SKY.
{
    m_modelRepos[_numberOfObstacles] = new GameModel(_drawEngine,ngl::Vec3(0,0,0),ngl::Vec4(0,0,0,1),ngl::Vec4(100,0,300,1),"models/ground_plane.obj","textures/grass.jpg",MODEL_BGS);
    _numberOfObstacles++;
    m_modelRepos[_numberOfObstacles] = new GameModel(_drawEngine,ngl::Vec3(0,-50,0),ngl::Vec4(0,0,0,1),ngl::Vec4(50,50,50,1),"models/ammunition.obj","textures/SkyBox_Clouds.png",MODEL_SKY);
}
void GameLevel::addCollisionBoxes ()
add the bullet collision boxes for all models
Definition at line 238 of file GameLevel.cpp.
References _physicsEngine, GamePhysicsEngine::addBox(), GamePhysicsEngine::addConvexGrenade(), GamePhysicsEngine::addConvexStones(), GamePhysicsEngine::addGround(), BOUNDARY_WALL_BACK, CRATE_AMMUNITION, INVISIBLE_WALL, m_graphicRepos, m_modelRepos, MODEL_BGS, MODEL_CRATEBOX, MODEL_OBSTACLE, and MODEL_PLAYER.
{
    ngl::Vec3 pos = 0;
    ngl::Vec3 rot = 0;
    ngl::Vec4 scale = 0;
    for(int i=0;i<m_modelRepos.size();i++)
    {
         pos = m_modelRepos[i]->getPosition();
         scale = m_modelRepos[i]->getScale();
         rot = m_modelRepos[i]->getRotation();
         std::cout<<"scale is :"<<scale;
         switch(m_modelRepos[i]->getModelName())
         {
            case MODEL_PLAYER:
            {
                _physicsEngine->addConvexGrenade(pos);
                break;
            }
            case MODEL_OBSTACLE:
            {
                _physicsEngine->addConvexStones(pos,rot);
                break;
            }
            case MODEL_CRATEBOX:
            {
                _physicsEngine->addBox(pos,(scale * 10),CRATE_AMMUNITION);  // this 10 has to be given appropriate value if ammunition box is scaled
                break;
            }
            case MODEL_BGS:
            {
                _physicsEngine->addGround(pos);
                break;
            }
         }
     }
        // add all 3 walls - left, right and far beyond the last goal - crate box
        _physicsEngine->addBox(ngl::Vec3(250,0,-100),ngl::Vec4(10,1000,1000,1),INVISIBLE_WALL); // change the 1000 and 2 to constant values
        _physicsEngine->addBox(ngl::Vec3(-250,0,-100),ngl::Vec4(10,1000,1000,1),INVISIBLE_WALL);
        _physicsEngine->addBox(ngl::Vec3(0,0,m_graphicRepos[BOUNDARY_WALL_BACK]->getPosition().m_z),ngl::Vec4(1000,1000,10,1),INVISIBLE_WALL);
}
void GameLevel::addCrateBoxToLevel ()
add the cratebox mesh to level
Definition at line 170 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, m_modelRepos, GameModelFactory::makeGameModel(), and MODEL_CRATEBOX.
{
    m_modelRepos[_numberOfObstacles] = GameModelFactory::makeGameModel(MODEL_CRATEBOX);
    m_modelRepos[_numberOfObstacles]->setDrawArea(_drawEngine);
    m_modelRepos[_numberOfObstacles]->setPosition(ngl::Vec3(-80,0,m_modelRepos[_numberOfObstacles - 1]->getPosition().m_z + 380));
     _numberOfObstacles++;
}
void GameLevel::addGraphicImages ()
add graphic images such as the bounding bunkers and the direction arrows
Definition at line 366 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, BOUNDARY_WALL_BACK, BOUNDARY_WALL_LEFT, BOUNDARY_WALL_RIGHT, DIRECTION_ARROW, m_graphicRepos, m_modelRepos, and MODEL_GRAPHICS.
{
    m_graphicRepos[DIRECTION_ARROW] = new GameModel(_drawEngine,ngl::Vec3(0,0,0),/*_physicsEngine->getPosition(MODEL_PLAYER),*/ngl::Vec4(0,0,0,1),ngl::Vec4(3,1,3,1),"models/arrow.obj","textures/Stone.png",MODEL_GRAPHICS);
    m_graphicRepos[BOUNDARY_WALL_LEFT] = new GameModel(_drawEngine,ngl::Vec3(250,0,-100),ngl::Vec4(0,90,0,1),ngl::Vec4(10,10,10,1),"models/sandbags_02.obj","textures/sandbags.jpg",MODEL_GRAPHICS);
    m_graphicRepos[BOUNDARY_WALL_RIGHT] = new GameModel(_drawEngine,ngl::Vec3(-250,0,-100),ngl::Vec4(0,-90,0,1),ngl::Vec4(10,10,10,1),"models/sandbags_02.obj","textures/sandbags.jpg",MODEL_GRAPHICS);
    // the back wall of the world is always placed beyond the last obstacle..so this is not hardcoded..each time the final crate box' position changes, our world's back wall will change accordingly
    m_graphicRepos[BOUNDARY_WALL_BACK] = new GameModel(_drawEngine,ngl::Vec3(0,0,m_modelRepos[_numberOfObstacles - 2]->getPosition().m_z + 3),ngl::Vec4(0,0,0,1),ngl::Vec4(10,10,10,1),"models/sandbags_02.obj","textures/sandbags.jpg",MODEL_GRAPHICS);
}
void GameLevel::addObstaclesToLevel ()
add the obstacle mesh to level
Definition at line 137 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, BEGINNER, m_difficulty, m_modelRepos, GameModelFactory::makeGameModel(), and MODEL_OBSTACLE.
{
    ngl::Random *randObj = ngl::Random::instance();
    if (m_difficulty == BEGINNER)
    {
        _numberOfObstacles = randObj->randomPositiveNumber(20);
    }
    else
    {
        _numberOfObstacles = randObj->randomPositiveNumber(25);
    }
   for(int i=1;i<=_numberOfObstacles;i++) // 0th pos is reserved for PLAYER,so obstacle shud not be inserted
                                          //hence loop from i=1
   {
        std::cout<<"coming in addobstacles";
        if ( i != 1)
        {
            m_modelRepos[i] = m_modelRepos[i - 1]->cloneItself();
        }
        else
        {
            m_modelRepos[i] = GameModelFactory::makeGameModel(MODEL_OBSTACLE);
            m_modelRepos[i]->setDrawArea(_drawEngine);
        }
    }
    _numberOfObstacles++;
}
void GameLevel::addPlayerToLevel ()
add the grenade mesh to level
Definition at line 125 of file GameLevel.cpp.
References _drawEngine, _player, m_modelRepos, GameModelFactory::makeGameModel(), and MODEL_PLAYER.
{
    m_modelRepos[MODEL_PLAYER] = GameModelFactory::makeGameModel(MODEL_PLAYER);
    m_modelRepos[MODEL_PLAYER]->setDrawArea(_drawEngine);
    _player = m_modelRepos[MODEL_PLAYER];
}
void GameLevel::drawExtras () [private]
draw module to draw all the extras such as graphic images and anti bullet objs
Definition at line 382 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, _physicsEngine, arrowDraw, BOUNDARY_WALL_BACK, BOUNDARY_WALL_LEFT, BOUNDARY_WALL_RIGHT, DIRECTION_ARROW, GameDrawEngine::drawModels(), GamePhysicsEngine::getPosition(), GamePhysicsEngine::getSimulationFlag(), loadModelsWithoutBulletTransformations(), m_graphicRepos, and m_modelRepos.
{
     ngl::TransformStack tempTransformStack;
    for(int i=0;i<m_graphicRepos.size();i++)
    {
        switch (i)
        {
        case DIRECTION_ARROW:
            if((arrowDraw == 1) && (_physicsEngine->getSimulationFlag() == 0)) // just to make sure the grenade is not in air while direction arrow is drawn
            {
            tempTransformStack = m_graphicRepos[DIRECTION_ARROW]->getTransformStack();
            loadModelsWithoutBulletTransformations(tempTransformStack,_physicsEngine->getPosition(0),m_graphicRepos[DIRECTION_ARROW]->getRotation(),m_graphicRepos[DIRECTION_ARROW]->getScale());
            _drawEngine->drawModels(m_graphicRepos[DIRECTION_ARROW]);
            }
            break;
        case BOUNDARY_WALL_LEFT:
            tempTransformStack = m_graphicRepos[BOUNDARY_WALL_LEFT]->getTransformStack();
            for (float i = -250; i <= 250;i=i+55)
            {
                loadModelsWithoutBulletTransformations(tempTransformStack,ngl::Vec3(m_graphicRepos[BOUNDARY_WALL_LEFT]->getPosition().m_x,0,i),m_graphicRepos[BOUNDARY_WALL_LEFT]->getRotation(),m_graphicRepos[BOUNDARY_WALL_LEFT]->getScale());
                _drawEngine->drawModels(m_graphicRepos[BOUNDARY_WALL_LEFT]);
            }
            break;
        case BOUNDARY_WALL_RIGHT:
            tempTransformStack = m_graphicRepos[BOUNDARY_WALL_RIGHT]->getTransformStack();
            for (float i = -250; i <= 250;i=i+55)
            {
                loadModelsWithoutBulletTransformations(tempTransformStack,ngl::Vec3(m_graphicRepos[BOUNDARY_WALL_RIGHT]->getPosition().m_x,0,i),m_graphicRepos[BOUNDARY_WALL_RIGHT]->getRotation(),m_graphicRepos[BOUNDARY_WALL_RIGHT]->getScale());
                _drawEngine->drawModels(m_graphicRepos[BOUNDARY_WALL_RIGHT]);
            }
            break;
        case BOUNDARY_WALL_BACK:
            tempTransformStack = m_graphicRepos[BOUNDARY_WALL_BACK]->getTransformStack();
            for (float i = -250; i <= 250;i=i+55)
            {
                loadModelsWithoutBulletTransformations(tempTransformStack,ngl::Vec3(i,0,m_graphicRepos[BOUNDARY_WALL_BACK]->getPosition().m_z),m_graphicRepos[BOUNDARY_WALL_BACK]->getRotation(),m_graphicRepos[BOUNDARY_WALL_BACK]->getScale());
                 _drawEngine->drawModels(m_graphicRepos[BOUNDARY_WALL_BACK]);
            }
            break;
        default:
            break;
        }
    }
    // drawing SKY BOX which is our last obstacle in the model repository
    loadModelsWithoutBulletTransformations(m_modelRepos[_numberOfObstacles]->getTransformStack(),m_modelRepos[_numberOfObstacles]->getPosition(),m_modelRepos[_numberOfObstacles]->getRotation(),m_modelRepos[_numberOfObstacles]->getScale());
    _drawEngine->drawModels(m_modelRepos[_numberOfObstacles]);
}
void GameLevel::drawLevel ()
draw the level
Definition at line 38 of file GameLevel.cpp.
References _drawEngine, _numberOfObstacles, _physicsEngine, CAM_DEFAULT, CAM_LEFT, CAM_RIGHT, CAM_TOP, drawExtras(), GameDrawEngine::drawModels(), GameDrawEngine::getActiveCam(), GamePhysicsEngine::getCollisionShape(), GamePhysicsEngine::getGameWonFlag(), GamePhysicsEngine::getNumCollisionObjects(), GamePhysicsEngine::getPosition(), GameDrawEngine::getSpecificCam(), GamePhysicsEngine::getTransformMatrix(), m_freeCamFlag, m_modelRepos, m_transformStack, and MODEL_CRATEBOX.
{
    ngl::Transformation trans;
    unsigned int bodies=_physicsEngine->getNumCollisionObjects();
    ngl::Mat4 MVP;
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    (*shader)["Texture"]->use();
    for(int i=0; (i<bodies) && (i<= _numberOfObstacles); ++i)
    {
        trans.setMatrix(_physicsEngine->getTransformMatrix(i));
        m_transformStack.setCurrent(trans);
        if ((i==0) && (m_freeCamFlag == 0))
        {
           ngl::Vec3 grenadeCurrentPos = _physicsEngine->getPosition(i);
           if((_drawEngine->getActiveCam() == _drawEngine->getSpecificCam(CAM_DEFAULT)))
            {
                _drawEngine->getActiveCam()->setEye(ngl::Vec4((grenadeCurrentPos.m_x),30,(grenadeCurrentPos.m_z - 40)));
            }
            else if((_drawEngine->getActiveCam() == _drawEngine->getSpecificCam(CAM_TOP)))
            {
                 _drawEngine->getActiveCam()->setEye(ngl::Vec4(grenadeCurrentPos.m_x,200,grenadeCurrentPos.m_z,1));
            }
            else if((_drawEngine->getActiveCam() == _drawEngine->getSpecificCam(CAM_LEFT)))
            {
                _drawEngine->getActiveCam()->setEye(ngl::Vec4((grenadeCurrentPos.m_x + 80),30,grenadeCurrentPos.m_z,1));
            }
            else if((_drawEngine->getActiveCam() == _drawEngine->getSpecificCam(CAM_RIGHT)))
            {
                _drawEngine->getActiveCam()->setEye(ngl::Vec4((grenadeCurrentPos.m_x - 80),30,grenadeCurrentPos.m_z,1));
            }
     }
     MVP= m_transformStack.getCurrentTransform().getMatrix() * _drawEngine->getActiveCam()->getVPMatrix(); //m_modelRepos[_modelIndex]->getCam()->getVPMatrix() ;
     shader->setShaderParamFromMat4("qt_ModelViewProjectionMatrix",MVP);
     switch(_physicsEngine->getCollisionShape(i))
     {
       case BOX_SHAPE_PROXYTYPE :
        {
            if ((m_modelRepos[i]->getModelName() == MODEL_CRATEBOX) && (_physicsEngine->getGameWonFlag() == false))
            {
                _drawEngine->drawModels(m_modelRepos[i]);
            }
            break;
        }
       case CONVEX_HULL_SHAPE_PROXYTYPE:
        {
            _drawEngine->drawModels(m_modelRepos[i]);
            break;
        }
        case STATIC_PLANE_PROXYTYPE:
        {
            ngl::TransformStack tempTransformation = m_modelRepos[i]->getTransformStack();
            tempTransformation.pushTransform();
            {
                tempTransformation.getCurrentTransform().setPosition(m_modelRepos[i]->getPosition());
                tempTransformation.getCurrentTransform().setRotation(m_modelRepos[i]->getRotation());
                tempTransformation.getCurrentTransform().setScale(m_modelRepos[i]->getScale());
                MVP= tempTransformation.getCurrentTransform().getMatrix() * _drawEngine->getActiveCam()->getVPMatrix(); //m_modelRepos[_modelIndex]->getCam()->getVPMatrix() ;
                shader->setShaderParamFromMat4("qt_ModelViewProjectionMatrix",MVP);
                _drawEngine->drawModels(m_modelRepos[i]);
            }
            tempTransformation.popTransform();
            break;
        }
      }
    }
    drawExtras();
}
float GameLevel::getAccumulatedDirection ()
get accumulated direction
GAME_LEVELS GameLevel::getLevelNumber ()
get the level number
Definition at line 198 of file GameLevel.cpp.
References m_levelNumber.
{
    return m_levelNumber;
}
GameModel * GameLevel::getPlayer ()
get reference to player
Definition at line 132 of file GameLevel.cpp.
References _player.
{
    return _player;
}
void GameLevel::loadModelsWithoutBulletTransformations (ngl::TransformStack _transformStack, const ngl::Vec3 & _pos, const ngl::Vec4 & _rot, const ngl::Vec4 & _scale) [private]
load the models which does not have anything to do with bullet using its own transform stack
Parameters:
[in] _transformStack transform of the current model
[in] _pos input position
[in] _rot rotation
[in] _scale scale
Definition at line 453 of file GameLevel.cpp.
References _drawEngine, and GameDrawEngine::getActiveCam().
{
    ngl::Mat4 MVP;
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    {
    _transformStack.getCurrentTransform().setPosition(_pos);
    _transformStack.getCurrentTransform().setRotation(_rot);
    _transformStack.getCurrentTransform().setScale(_scale);
    MVP= _transformStack.getCurrentTransform().getMatrix() * _drawEngine->getActiveCam()->getVPMatrix(); //m_modelRepos[_modelIndex]->getCam()->getVPMatrix() ;
    shader->setShaderParamFromMat4("qt_ModelViewProjectionMatrix",MVP);
    }
}
void GameLevel::moveGrenade (int _windValue)
Definition at line 292 of file GameLevel.cpp.
References _physicsEngine, accumulatedAcceleration, accumulatedDirection, and GamePhysicsEngine::moveGrenade().
{
    // if its level3 call this func with 3 args..so third arg as to be got via a random number generator
    _physicsEngine->moveGrenade((accumulatedDirection),accumulatedAcceleration,_windValue);
}
void GameLevel::moveGrenade ()
move grenade oveloaded function to include wind factor
Definition at line 285 of file GameLevel.cpp.
References _physicsEngine, accumulatedAcceleration, accumulatedDirection, and GamePhysicsEngine::moveGrenade().
{
    // if its level3 call this func with 3 args..so third arg as to be got via a random number generator
    _physicsEngine->moveGrenade((accumulatedDirection),accumulatedAcceleration);
}
void GameLevel::moveObstacles ()
move obstacles
void GameLevel::setArrowDrawFlag (int _inputKey)
set the arrow direction arrow draw flag
Parameters:
[in] _inputKey
Definition at line 300 of file GameLevel.cpp.
References arrowDraw.
{
    arrowDraw = _inputKey;
   // std::cout<<"arrow key state is \n"<<arrowDraw;
}
void GameLevel::setFreeCamFlag (int _inputFreeCamFlag)
set the free cam flag
Definition at line 471 of file GameLevel.cpp.
References m_freeCamFlag.
{
    m_freeCamFlag = _inputFreeCamFlag;
}
void GameLevel::setLevelCam (ngl::Camera * _cam)
set the level camera
Parameters:
[in] _cam camera input
void GameLevel::setLevelDifficulty (DIFFICULTY_LEVELS _difficulty)
creates the specified model
Parameters:
[in] _difficulty difficulty level
Definition at line 188 of file GameLevel.cpp.
References m_difficulty.
{
    m_difficulty = _difficulty;
}
void GameLevel::setLevelNumber (GAME_LEVELS _inputLevelNumber)
set the level number
Parameters:
[in] _inputLevelNumber input level number
Definition at line 193 of file GameLevel.cpp.
References m_levelNumber.
{
    m_levelNumber = _inputLevelNumber;
}
void GameLevel::simulateAI ()
move models randomly for level 3
Definition at line 203 of file GameLevel.cpp.
References _numberOfObstacles, _physicsEngine, m_modelRepos, MODEL_OBSTACLE, and GamePhysicsEngine::moveBox().
{
    static int x = 0; // temp variable to delay change in direction of tank movements in level3
    static float velocity = 0.1;
    if (  x > 100)
    {
        x = 0;
        velocity = (-velocity);
    }
    for(int i=0;i<=_numberOfObstacles;i++)
    {
         if((i+1) <= _numberOfObstacles)
         {
            switch(m_modelRepos[i + 1]->getModelName())
            {
                case MODEL_OBSTACLE:
                {
                     _physicsEngine->moveBox((i + 1),velocity); // according to bullet, our obstacles start from 2, so i + 1
                      break;
                }
                default:
                    break;
            }
        }
    }
    x++;
}
Member Data Documentation
GameDrawEngine* GameLevel::_drawEngine [private]
drawing engine
Definition at line 196 of file GameLevel.h.
int GameLevel::_numberOfObstacles [private]
_total number of obstacles
Definition at line 180 of file GameLevel.h.
GamePhysicsEngine* GameLevel::_physicsEngine [private]
model repository with enum key
Definition at line 200 of file GameLevel.h.
GameModel* GameLevel::_player [private]
player pointer
Definition at line 192 of file GameLevel.h.
int GameLevel::_screenHeight [private]
screen ht
Definition at line 172 of file GameLevel.h.
int GameLevel::_screenWidth [private]
screen wdth
Definition at line 176 of file GameLevel.h.
int GameLevel::accumulatedAcceleration [private]
total accumulated acceleration from the user keypress
Definition at line 216 of file GameLevel.h.
int GameLevel::accumulatedDirection [private]
total accumulated direction from the user keypress
Definition at line 212 of file GameLevel.h.
int GameLevel::arrowDraw [private]
flag to check whether to draw the arrow/ not drawn during simulation
Definition at line 208 of file GameLevel.h.
DIFFICULTY_LEVELS GameLevel::m_difficulty [private]
enum difficulty levels
Definition at line 184 of file GameLevel.h.
int GameLevel::m_freeCamFlag [private]
flag to check if free cam is enabled/disabled
Definition at line 220 of file GameLevel.h.
std::map<int, GameModel*> GameLevel::m_graphicRepos [protected]
graphic image repository with enum key
Definition at line 165 of file GameLevel.h.
GAME_LEVELS GameLevel::m_levelNumber [private]
current level number
Definition at line 188 of file GameLevel.h.
std::map<int,GameModel *> GameLevel::m_modelRepos [protected]
model repository with enum key
Definition at line 161 of file GameLevel.h.
ngl::TransformStack GameLevel::m_transformStack [private]
transform stack of the corresponding model
Definition at line 204 of file GameLevel.h.
The documentation for this class was generated from the following files:
GameLevel.h
GameLevel.cpp