GRENADE GAME: GameLogic Class Reference
GameLogic Class Reference
GameLogic class handles all the logical things such as processing the keys recieved from GameControls, the main game logic of reduction of score, contact with physics engine to query status and the important GL functions of initialize,paint and resize functions. This acts as the hub between Physics engine and the controls classes.Inherits QGLWidget.
#include <GameLogic.h>
Public Member Functions
GameLogic (QWidget *_parent)
Constructor for GLWindow.
~GameLogic ()
dtor add any code here to tidy up
void processKeyDown (QKeyEvent *_event)
processKeyDown passed from the main window class
void processKeyUp (QKeyEvent *_event)
processKeyUp passed from the main window class
void setDifficulty (DIFFICULTY_LEVELS _difficulty)
set the current difficulty
void setLevel (int _inputLevel)
set the currnt level from ui
void changeCamera (CAMERA_NAMES _camName)
change the camera
int getGameStartedFlag ()
gets the flag to check if the game is started or not
bool getSimulationFlag ()
gets the flag to check if the game is in simulation(in air)
void setWindValue (int _inputWindValue)
sets the wind value
float getCurrentGrenadeLife ()
gets the grande life
bool getGameWonFlag ()
gets the game won flag when queried
void setFreeCamFlag (int _inputFreeCamFlag)
set detach camera flag
void setGameLostFlag ()
sets game lost flag from ui score check
bool getGameLostFlag ()
gets the game lost flag to display appropriate message to usr
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Private Member Functions
void timerEvent (QTimerEvent *_event)
the timer event triggered from the timers
Private Attributes
int m_updateGrenadeTimer
a timer triggered by the startTimer call in the ctor this is called to update the player position based on the key presses
int m_redrawTimer
a timer triggered by the startTimer call in the ctor this is called to redraw the level
int progressTimer
a timer triggered by the startTimer call in the ctor this is called to mark the loading progress
ngl::Camera * m_cam
all cameras
ngl::Camera * m_cam1
ngl::Camera * m_cam2
ngl::Camera * m_cam3
GameModel * m_grenade
pointer to player
QSet< Qt::Key > m_keysPressed
the keys being pressed
GameDrawEngine * drawEngine
drawengine ptr
GamePhysicsEngine * physicsWorld
physics world ptr
GameLevel * level
level pointer
DIFFICULTY_LEVELS difficulty
enum difficulty level
GAME_LEVELS m_levelNumber
level number
int gameStarted
game started flag
int windValue
wind value from ui
ngl::Text * m_text
win/lost text pointer
bool lostFlag
game lost flag
Detailed Description
GameLogic class handles all the logical things such as processing the keys recieved from GameControls, the main game logic of reduction of score, contact with physics engine to query status and the important GL functions of initialize,paint and resize functions. This acts as the hub between Physics engine and the controls classes.Inherits QGLWidget.
Definition at line 39 of file GameLogic.h.
Constructor & Destructor Documentation
GameLogic::GameLogic (QWidget * _parent)
Constructor for GLWindow.
Parameters:
[in] parent the parent window to create the GL context in
Definition at line 10 of file GameLogic.cpp.
References BEGINNER, difficulty, gameStarted, LEVEL1, lostFlag, m_keysPressed, m_levelNumber, physicsWorld, GamePhysicsEngine::setGrenadeObstacleCcount(), and windValue.
                         : QGLWidget( new CreateCoreGLContext(QGLFormat::defaultFormat()), _parent )
{
    //def constructor
    // set this widget to have the initial keyboard focus
    setFocus();
    // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
    this->resize(_parent->size());
    difficulty = BEGINNER;
    m_levelNumber = LEVEL1;
    m_keysPressed.clear();
    physicsWorld = new GamePhysicsEngine();
    gameStarted = 0;
    windValue = 0;
    physicsWorld->setGrenadeObstacleCcount(100);
    lostFlag = false;
}
GameLogic::~GameLogic ()
dtor add any code here to tidy up
Definition at line 34 of file GameLogic.cpp.
References m_redrawTimer, and progressTimer.
{
    // call the static NGLQuit method to close down
    // NGL and tidy up any shaders textures etc
    // first get an instance of the NGLInit singleton
    killTimer(m_redrawTimer);
    killTimer(progressTimer);
    ngl::NGLInit *ngl = ngl::NGLInit::instance();
    // then call the quit method
    ngl->NGLQuit();
}
Member Function Documentation
void GameLogic::changeCamera (CAMERA_NAMES _camName)
change the camera
Parameters:
_camName cam name
Definition at line 360 of file GameLogic.cpp.
References drawEngine, and GameDrawEngine::setActiveCam().
{
    drawEngine->setActiveCam(_camName);
}
float GameLogic::getCurrentGrenadeLife ()
gets the grande life
Definition at line 384 of file GameLogic.cpp.
References GamePhysicsEngine::getGrenadeObstacleCcount(), and physicsWorld.
{
    return physicsWorld->getGrenadeObstacleCcount();
}
bool GameLogic::getGameLostFlag ()
gets the game lost flag to display appropriate message to usr
Definition at line 407 of file GameLogic.cpp.
References lostFlag.
{
    return lostFlag;
}
int GameLogic::getGameStartedFlag ()
gets the flag to check if the game is started or not
Definition at line 367 of file GameLogic.cpp.
References gameStarted.
{
    return gameStarted;
}
bool GameLogic::getGameWonFlag ()
gets the game won flag when queried
Definition at line 389 of file GameLogic.cpp.
References GamePhysicsEngine::getGameWonFlag(), and physicsWorld.
{
    return physicsWorld->getGameWonFlag();
}
bool GameLogic::getSimulationFlag ()
gets the flag to check if the game is in simulation(in air)
Definition at line 372 of file GameLogic.cpp.
References GamePhysicsEngine::getSimulationFlag(), and physicsWorld.
{
    return (physicsWorld->getSimulationFlag());
}
void GameLogic::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
Definition at line 57 of file GameLogic.cpp.
References GameLevel::addBGToLevel(), GameDrawEngine::addCamToRepos(), GameLevel::addCollisionBoxes(), GameLevel::addCrateBoxToLevel(), GameLevel::addGraphicImages(), GameLevel::addObstaclesToLevel(), GameLevel::addPlayerToLevel(), CAM_DEFAULT, CAM_LEFT, CAM_RIGHT, CAM_TOP, changeCamera(), difficulty, drawEngine, gameStarted, GameLevel::getPlayer(), level, m_cam, m_cam1, m_cam2, m_cam3, m_grenade, m_keysPressed, m_levelNumber, m_redrawTimer, physicsWorld, GameLevel::setLevelDifficulty(), and GameLevel::setLevelNumber().
{
  glClearColor(0.4f, 0.4f, 0.4f, 1.0f); // Black Background
  // enable depth testing for drawing
  glEnable(GL_DEPTH_TEST);
  // we need to initialise the NGL lib, under windows and linux we also need to
  // initialise GLEW, under windows this needs to be done in the app as well
  // as the lib hence the WIN32 define
  ngl::NGLInit *Init = ngl::NGLInit::instance();
  Init->initGlew();    m_keysPressed.clear();
  #ifdef WIN32
    glewInit(); // need a local glew init as well as lib one for windows
  #endif
//  // now to load the shader and set the values
//  // grab an instance of shader manager
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  // we are creating a shader called Texture
  shader->createShaderProgram("Texture");
  // now we are going to create empty shaders for Frag and Vert
  shader->attachShader("TextureVertex",ngl::VERTEX);
  shader->attachShader("TextureFragment",ngl::FRAGMENT);
  // attach the source
  shader->loadShaderSource("TextureVertex","shaders/TextureVertex.glsl");
  shader->loadShaderSource("TextureFragment","shaders/TextureFragment.glsl");
  // compile the shaders
  shader->compileShader("TextureVertex");
  shader->compileShader("TextureFragment");
  // add them to the program
  shader->attachShaderToProgram("Texture","TextureVertex");
  shader->attachShaderToProgram("Texture","TextureFragment");
  // now we have associated this data we can link the shader
  shader->linkProgramObject("Texture");
  // and make it active ready to load values
  (*shader)["Texture"]->use();
  // Now we will create a basic Camera from the graphics library
  // This is a static camera so it only needs to be set once
  // First create Values for the camera position
  ngl::Vec3 from_cam1(0,20,-80);//20,-80
  ngl::Vec3 to_cam1(0,0,0);
  ngl::Vec3 up_cam1(0,1,0);
  // now load to our new camera
  m_cam= new ngl::Camera(from_cam1,to_cam1,up_cam1,ngl::PERSPECTIVE);
  // set the shape using FOV 45 Aspect Ratio based on Width and Height
  // The final two are near and far clipping planes of 0.5 and 10
  m_cam->setShape(45,(float)1024.0/720.0,0.05,350,ngl::PERSPECTIVE);
  ngl::Vec3 from_cam2(30,30,-50);
  ngl::Vec3 to_cam2(0,0,0);
  ngl::Vec3 up_cam2(0,1,0);
  m_cam1 = new ngl::Camera(from_cam2,to_cam2,up_cam2,ngl::PERSPECTIVE);
  m_cam1->setShape(90,(float)1024.0/720.0,0.05,350,ngl::PERSPECTIVE);
  m_cam1->yaw(60);
  m_cam1->roll(25);
  ngl::Vec3 from_cam3(0,200,-10);
  ngl::Vec3 to_cam3(0,0,0);
  ngl::Vec3 up_cam3(0,1,0);
  m_cam2 = new ngl::Camera(from_cam3,to_cam3,up_cam3,ngl::PERSPECTIVE);
  m_cam2->setShape(45,(float)1024.0/720.0,0.05,350,ngl::PERSPECTIVE); // change camera value to accomodate mor viewing angle from top, may be set projection
  ngl::Vec3 from_cam4(-30,30,-50);
  ngl::Vec3 to_cam4(0,0,0);
  ngl::Vec3 up_cam4(0,1,0);
  m_cam3 = new ngl::Camera(from_cam4,to_cam4,up_cam4,ngl::PERSPECTIVE);
  m_cam3->setShape(90,(float)1024.0/720.0,0.05,350,ngl::PERSPECTIVE);
  m_cam3->yaw(-60);
  m_cam3->roll(-25);
  shader->setShaderParam3f("viewerPos",m_cam->getEye().m_x,m_cam->getEye().m_y,m_cam->getEye().m_z);
  drawEngine = new GameDrawEngine(1024,780);
  level = new GameLevel(drawEngine,physicsWorld,1024,780);
  level->setLevelDifficulty(difficulty);
  level->setLevelNumber(m_levelNumber);
  level->addPlayerToLevel();
  m_grenade = level->getPlayer();
  level->addObstaclesToLevel(); // change this based on difficulty
  level->addCrateBoxToLevel();
  level->addBGToLevel();
  drawEngine->addCamToRepos(CAM_DEFAULT,m_cam);
  drawEngine->addCamToRepos(CAM_LEFT,m_cam1);
  drawEngine->addCamToRepos(CAM_TOP,m_cam2);
  drawEngine->addCamToRepos(CAM_RIGHT,m_cam3);
  changeCamera(CAM_DEFAULT);
  level->addGraphicImages();
  level->addCollisionBoxes();
  gameStarted = 1;
m_redrawTimer = startTimer(10);
}
void GameLogic::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Definition at line 187 of file GameLogic.cpp.
References GameLevel::drawLevel(), getGameWonFlag(), GameLevel::getLevelNumber(), level, LEVEL3, lostFlag, lostText(), m_text, GameLevel::simulateAI(), winningText(), and winningText2().
{
  // clear the screen and depth buffer
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  level->drawLevel();
  if(level->getLevelNumber() == LEVEL3) // jus for prototypes..change it to more appropriate switch case when more levels are developed
  {
      level->simulateAI();
  }
  if(getGameWonFlag() == true)
  {
      static int counter = 1;
      static int color = 1;
      m_text = new ngl::Text(QFont("PakTypeNaqsh",30));
      m_text->setColour(color,color,color);
      if ( counter == 50)
      {
          counter = 1;
          color = -color;
      }
      m_text->renderText(20,20,winningText);
      m_text->renderText(20,50,winningText2);
      counter++;
  }
  if (lostFlag == true)
  {
      static int lostColorCounter = 1;
      static int lostColor = 1;
      m_text = new ngl::Text(QFont("PakTypeNaqsh",30));
      m_text->setColour(lostColor,lostColor,lostColor);
      if ( lostColorCounter == 50)
      {
       lostColorCounter = 1;
       lostColor = -lostColor;
      }
     m_text->renderText(50,50,lostText);
     lostColorCounter++;
  }
}
void GameLogic::processKeyDown (QKeyEvent * _event)
processKeyDown passed from the main window class
Parameters:
*_event a pointer to the QKeyEvent passed from main window class
Definition at line 262 of file GameLogic.cpp.
References GameLevel::accumulateAcceleration(), GameLevel::accumulateDirection(), CAM_DEFAULT, CAM_LEFT, CAM_RIGHT, CAM_TOP, changeCamera(), GameLevel::getLevelNumber(), level, m_keysPressed, GameLevel::moveGrenade(), GameLevel::setArrowDrawFlag(), and windValue.
{
    switch(_event->key())
    {
        case Qt::Key_1 : changeCamera(CAM_DEFAULT);break;
        case Qt::Key_2 : changeCamera(CAM_LEFT);break;
        case Qt::Key_3 : changeCamera(CAM_TOP);break;
        case Qt::Key_4 : changeCamera(CAM_RIGHT);break;
    case Qt::Key_Left:
    {
        level->setArrowDrawFlag(1);
        level->accumulateDirection(10);
        break;
    }
    case Qt::Key_Right:
    {
        level->setArrowDrawFlag(1);
        level->accumulateDirection(-10);
        break;
    }
    case Qt::Key_Up:
    {
        level->accumulateAcceleration(10);
        //moveGrenade();
        break;
    }
    case Qt::Key_Down:
    {
        level->accumulateAcceleration(-10);
        //moveGrenade();
        break;
    }
    case Qt::Key_Space:
    {
        level->setArrowDrawFlag(0);
        level->accumulateDirection(0);
        if (_event->isAutoRepeat() == 1)
        {
            break;
        }
        if (level->getLevelNumber() >= 2)
        {
        level->moveGrenade(windValue);
        }
        else
        {
           level->moveGrenade();
        }
        level->accumulateAcceleration(0);
        break;
    }
        default:break;
    }
    if ((_event->key() != Qt::Key_1) || (_event->key() != Qt::Key_2) )
    {
        // add to our keypress set the values of any keys pressed
        m_keysPressed += (Qt::Key)_event->key();
    }
}
void GameLogic::processKeyUp (QKeyEvent * _event)
processKeyUp passed from the main window class
Parameters:
*_event a pointer to the QKeyEvent passed from main window class
Definition at line 340 of file GameLogic.cpp.
References m_keysPressed.
{
    // remove from our key set any keys that have been released
    m_keysPressed -= (Qt::Key)_event->key();
}
void GameLogic::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
Parameters:
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 170 of file GameLogic.cpp.
References m_cam, and m_text.
{
  glViewport(0,0,_w,_h);
  //m_cam->setShape(45,(float)_w/_h,0.5,150,ngl::PERSPECTIVE);
  m_cam->setShape(45,(float)720.0/576.0,0.05,350,ngl::PERSPECTIVE);
  m_text->setScreenSize(_w,_h);
}
void GameLogic::setDifficulty (DIFFICULTY_LEVELS _difficulty)
set the current difficulty
Parameters:
_difficulty difficulty level from ui
Definition at line 349 of file GameLogic.cpp.
References difficulty.
{
    difficulty = _difficulty;
}
void GameLogic::setFreeCamFlag (int _inputFreeCamFlag)
set detach camera flag
Definition at line 395 of file GameLogic.cpp.
References level, and GameLevel::setFreeCamFlag().
{
    level->setFreeCamFlag(_inputFreeCamFlag);
}
void GameLogic::setGameLostFlag ()
sets game lost flag from ui score check
Definition at line 400 of file GameLogic.cpp.
References lostFlag.
{
    lostFlag = true;
}
void GameLogic::setLevel (int _inputLevel)
set the currnt level from ui
Parameters:
_inputLevel the current level
Definition at line 354 of file GameLogic.cpp.
References m_levelNumber.
{
    m_levelNumber = (GAME_LEVELS)_inputLevel;
}
void GameLogic::setWindValue (int _inputWindValue)
sets the wind value
Parameters:
_inputWindValue to set
Definition at line 378 of file GameLogic.cpp.
References windValue.
{
    windValue = _inputWindValue;
}
void GameLogic::timerEvent (QTimerEvent * _event) [private]
the timer event triggered from the timers
Parameters:
_even the event of the timer triggered by Qt
Definition at line 241 of file GameLogic.cpp.
References m_redrawTimer, physicsWorld, and GamePhysicsEngine::step().
{
    if (_event->timerId() == m_redrawTimer)
    {
    physicsWorld->step();
    updateGL();
    }
}
Member Data Documentation
DIFFICULTY_LEVELS GameLogic::difficulty [private]
enum difficulty level
Definition at line 208 of file GameLogic.h.
GameDrawEngine* GameLogic::drawEngine [private]
drawengine ptr
Definition at line 195 of file GameLogic.h.
int GameLogic::gameStarted [private]
game started flag
Definition at line 218 of file GameLogic.h.
GameLevel* GameLogic::level [private]
level pointer
Definition at line 203 of file GameLogic.h.
bool GameLogic::lostFlag [private]
game lost flag
Definition at line 234 of file GameLogic.h.
ngl::Camera* GameLogic::m_cam [private]
all cameras
Definition at line 181 of file GameLogic.h.
ngl::Camera * GameLogic::m_cam1 [private]
Definition at line 181 of file GameLogic.h.
ngl::Camera * GameLogic::m_cam2 [private]
Definition at line 181 of file GameLogic.h.
ngl::Camera * GameLogic::m_cam3 [private]
Definition at line 181 of file GameLogic.h.
GameModel* GameLogic::m_grenade [private]
pointer to player
Definition at line 187 of file GameLogic.h.
QSet<Qt::Key> GameLogic::m_keysPressed [private]
the keys being pressed
Definition at line 190 of file GameLogic.h.
GAME_LEVELS GameLogic::m_levelNumber [private]
level number
Definition at line 213 of file GameLogic.h.
int GameLogic::m_redrawTimer [private]
a timer triggered by the startTimer call in the ctor this is called to redraw the level
Definition at line 170 of file GameLogic.h.
ngl::Text* GameLogic::m_text [private]
win/lost text pointer
Definition at line 229 of file GameLogic.h.
int GameLogic::m_updateGrenadeTimer [private]
a timer triggered by the startTimer call in the ctor this is called to update the player position based on the key presses
Definition at line 164 of file GameLogic.h.
GamePhysicsEngine* GameLogic::physicsWorld [private]
physics world ptr
Definition at line 199 of file GameLogic.h.
int GameLogic::progressTimer [private]
a timer triggered by the startTimer call in the ctor this is called to mark the loading progress
Definition at line 176 of file GameLogic.h.
int GameLogic::windValue [private]
wind value from ui
Definition at line 224 of file GameLogic.h.
The documentation for this class was generated from the following files:
GameLogic.h
GameLogic.cpp